services:
  postgres:
    image: postgres
    container_name: rundeck_db
    restart: unless-stopped
    pull_policy: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rundeck
      POSTGRES_USER: rundeck
      POSTGRES_PASSWORD: changeme
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  rundeck:
    image: rundeck/rundeck:5.7.0
    container_name: rundeck
    pull_policy: always
    restart: unless-stopped
    environment:
      RUNDECK_DATABASE_DRIVER: org.postgresql.Driver
      RUNDECK_DATABASE_USERNAME: rundeck
      RUNDECK_DATABASE_PASSWORD: changeme
      RUNDECK_DATABASE_URL: jdbc:postgresql://postgres/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      RUNDECK_GRAILS_URL: https://localhost:4443
      RUNDECK_WITH_SSL: "true"
      RUNDECK_ADMIN_PASSWORD: "admin"
    healthcheck:
      test: "curl -f https://localhost:4443"
      interval: 5s
      timeout: 10s
      retries: 50
      start_period: 180s
      start_interval: 10s
    volumes:
      - rundeck-data:/home/rundeck/server/data
    ports:
      - "4443:4443"
    depends_on:
      postgres:
        condition: service_started

volumes:
  postgres-data:
    driver: local
  rundeck-data:
    driver: local

networks:
  default:
    external: true
    name: Secure